const SCREENS = {
    UPDATEPASS: 'UPDATEPASS',
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    PRODUCTLIST: 'PRODUCTLIST',
    HOME: 'Trang chủ',
    ORDERS: 'ORDERS',
    TABLESELECTION: 'TABLESELECTION',
    PRODUCTDETAIL: 'PRODUCTDETAIL',
    PAYMENT: 'PAYMENT',
    PROFILE: 'PROFILE',
    CONFIRMEMAIL: 'CONFIRMEMAIL',
    PROFILEME: 'PROFILESCREEN',
    CONFIRMEMAIL: 'CONFIRMEMAIL'
    
  };
  
  export default SCREENS;
  